//DEBUG FLAG
bool debug = false;

//CALCULATION CONSTANTS
const int READ_BUFFER_SIZE = 2048;
const int BAUD_RATE = 9600;

//GLOBAL PINS
const int TX = 0;
const int RX = 1;
const int LCD_SDA = 18;  //A4
const int LCD_SCL = 19;  //A5

//INSIDE DOOR SPECIFIC (STARTS WITH I)

//OUTSIDE DOOR SPECIFIC (STARTS WITH O)

//CONTROL HUB SPECIFIC (STARTS WITH C)